name: Train and Validate

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install wheel

      - name: Install project requirements
        run: |
          pip install -r requirements.txt

      - name: Run training
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          python train.py --outdir artifacts --seed 1 --C 1.0

      - name: Run validation
        run: |
          python model_validation.py
